name: Deploy Laravel Production

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Deploy Laravel
        run: |
          cd /var/www/test.etechdreams.com/test/testCICD

          echo "Starting deployment..."

          git fetch origin
          git reset --hard origin/main

          composer install \
            --no-dev \
            --prefer-dist \
            --no-interaction \
            --optimize-autoloader

          php artisan optimize:clear

          php artisan migrate 

          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          php artisan queue:restart || true

          echo "Deployment completed successfully."
