name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Production
    runs-on: self-hosted

    steps:
      - name: Deploy application
        run: |
          set -e

          cd /var/www/test.etechdreams.com/test/testCICD

          echo "===== Starting deployment ====="

          git fetch origin
          git reset --hard origin/main

          composer install \
            --no-dev \
            --prefer-dist \
            --no-interaction \
            --optimize-autoloader

          php artisan optimize:clear
          php artisan migrate --force

          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan optimize:clear

          php artisan queue:restart || true

          echo "===== Deployment successful ====="
